# اسم المشروع
spring.application.name=media-core


# ===============================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/media_saas_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:23.10@Cris!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================

spring.servlet.multipart.max-file-size=900MB
spring.servlet.multipart.max-request-size=900MB
server.tomcat.max-swallow-size=-1

spring.output.ansi.enabled=always